[package]
name = "mq-example"
version = "0.1.0"
edition = "2021"

[dependencies]
# apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
egui-macroquad = "0.11"
macroquad = "0.3"
